name: David Mazzarri
favicon: null
layout_spectrum: 0.9667851347476244
typography_spectrum: 0.1167583828791976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.17823799140751362
  lightness: 0.6617358466610312
  saturation: 0.0031646688003093004
  rhythmicContrast: 0.13105893251486123
purpose: []
