name: David Mazzarri
favicon: null
layout_spectrum: 0.25842
typography_spectrum: 0.1167583828791976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f442c'
    - '#dfe7ea'
    - '#6e5b53'
    - '#ac9a9a'
    - '#479693'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
